### PR TITLE
PSR code cleanup for Sensiolabs Insight platinum badge

### PR DESCRIPTION
**Pull request by mxnr**
Here is a result of Sensiolabs Insight check - https://insight.sensiolabs.com/projects/c63893b1-6db0-4004-a8da-e0703103f7b4

### CODE REVIEW

**Comment by alexdebril** [comment]
Hello,

Thank you very much for this excellent PR. The only issue some users will need to deal with is the compatibility break due to the ItemInterface renaming.

I will merge the PR and write a release note to explain how to fix the compatibility break if it happens.

Cheers,

Alex

**Comment by mxnr** [comment]
Cool, thanks Alex!

**Comment by Soullivaneuh** [comment]
@alexdebril @mxnr according to [Semantic Versioning](http://semver.org/), BC breaks introducing should be put on a new **major** version (e.g. 2.0).

The best is to put some deprecated alerts on 1.7 instead.

BTW, it's already done so let get it as is, I just want to advice you for next one. :+1:

**Comment by alexdebril** [comment]
You're right, thank you for this advice.

**Pull request merged**
