### PR TITLE
Moved XML parsing to XmlParser service

### PR DESCRIPTION
**Pull request by romaricdrigon**
Hi,

Following #92 

BC break: constructor of `FeedReader` changed.

### CODE REVIEW

**Comment by alexdebril** [comment]
HI,

The build failed with the following error : 

PHP Fatal error:  Class 'Debril\RssAtomBundle\Protocol\Parser\XmlParser' not found in /home/travis/build/alexdebril/rss-atom-bundle/Tests/Protocol/FeedReaderTest.php on line 27

Have you forgot a use statement in the unit test or something like that ?

Cheers,

**Comment by romaricdrigon** [comment]
Indeed there was an issue about a case sensitive filename., that's now fixed!

**Comment by romaricdrigon** [comment]
Any hope about getting that one merged soon?

**Comment by alexdebril** [comment]
Thank You Romaric (and sorry for the delay).

Do you think the BC break justifies a major version upgrade? I'm not sure about that as it is transparent for those who use the service container. Do you see any use-case where creating the FeedReader instance yourself would be relevant?

**Comment by romaricdrigon** [comment]
Only case I would see would break is persons that overrode - totally - `FeedReader`. It's something that could be, but also something pretty "internal". There's no public API or such promise, so I would say no need for a major release.

**Pull request merged**
